---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-ubuntu-22
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns: host
  - name: instance-ubuntu-20
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns: host
  - name: instance-oraclelinux-8
    image: geerlingguy/docker-oraclelinux8-ansible:latest
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      local_tmp: /tmp
  playbooks:
    converge: converge.yml
    prepare: prepare.yml
    verify: verify.yml
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
