---
all:
  children:
    clickhouse:
      hosts:
        clickhouse-01:
          ansible_host: 130.193.34.184
          ansible_user: admin-devops
    vector:
      hosts:
        vector-01:
          ansible_host: 89.169.181.196
          ansible_user: admin-devops
    lighthouse:
      hosts:
        lighthouse-01:
          ansible_host: 89.169.182.17
          ansible_user: admin-devops
