galaxy_info:
  role_name: vector
  namespace: your_galaxy_username
  author: your_name
  description: Install and configure Vector
  company: your_company

  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "20.04"

  galaxy_tags:
    - vector
    - logging
    - observability
